---
# Workflow for colo-server-01 Ubuntu 24.04 installation
apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: colo-server-01-ubuntu
  namespace: tink-system
spec:
  templateRef: ubuntu-2404
  hardwareRef: colo-server-01
  hardwareMap:
    device_1: 00:0c:29:73:03:4b
    hostname: colo-server-01
  # Automatically disable PXE boot after workflow completes
  bootOptions:
    toggleAllowNetboot: true
---
# Workflow for anvil (Dell R610) Ubuntu 24.04 installation
apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: anvil-ubuntu
  namespace: tink-system
spec:
  templateRef: anvil-ubuntu-2404
  hardwareRef: anvil
  hardwareMap:
    device_1: 00:21:9b:a1:dc:c0
    hostname: anvil
  # Automatically disable PXE boot after workflow completes
  bootOptions:
    toggleAllowNetboot: true
---
# Workflow for anvil (Dell R610) Harvester HCI installation
apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: anvil-harvester
  namespace: tink-system
spec:
  templateRef: anvil-harvester
  hardwareRef: anvil
  hardwareMap:
    device_1: 00:21:9b:a1:dc:c0
    hostname: anvil
  bootOptions:
    toggleAllowNetboot: true
