---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgAyVy3Q0DLaRK7v5mnc2V219I49ZSj+xOHe3thFIbYuFlzA37uX+g6yvqCH+CimXFnJRAxdSn4emvngk+JkeXQvifbjj+fXTz2JkygynHSpJr9EwuCjI5ojb4DEy0ygH+76k8jhmx13g4O+nvgMZBwxo8KMk6mnWpPg5wvKAlviJ2kKys16UE9LXufSFIgnP3wUnAEJhJ79VHRga7cUvXY+gwsRr5XjpmwDqOZpm2V7eZqTpA9OkJwDL7xoP55yKzUDIFJ/01p1YXw0AR3B4y4FpvM4vOak/Ko4GOO4/x5R7qV6AidttlyzhuQI1UGqQFQOx7fT5wtxupJPogyM79OUU7YyqTMEj+NbfF/grt+MaJxqbVXYAKCJtSvbai+6lOdTdjx0ad0uFHw+qp4zv7ylaWivJHtIft/yTbVhWbdyMGEkLAJhJkP+ISrIP61Mo/ijmObulA72/iGuIsRUIZr7m3PG04Dys4vkn3Z2hjsW4iVU9wQICzkHCRiG7sy9FtRButu4VW1Jn8/Q/MOjZtFAoOyUBgygv7XkHtd6JzOsEvdOhvp21UpwhedtKzcv7yRgTfu7WgH9n+k+q1KBIypUiaIxJF2zqEDt13orIlwG3bsfddr9z3ZS9F4SRVSOZREf3SxNtVNb0OuFHxjQIloNmCNICNLiwGjepJ+YenEFMtnXtTsiYRGFNnuIiJkSjNkjkjrkzd3T48GJkhzXqxXb9VA9lw==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgA5y6JitgUV+jRqJK3CjHH1TGXTPa1FBo0eBIWHJNnRUChW+D/6QDcNnWZjn95Vui6Fkh5gaa+BY1dP5hsP9nXPiyXlr/hnCCCMV3eLFX0e+IM8lxfe7RXceKNqNxZtKQHtckY+4Leni5UMeewHxTjik0oVqqBpCm0h32GZXygPBnNHU4H+KFspbyZO17rVpfs9T5oICjqTJxJcQ6+UMd9rG7psE0hbLImn6CrowW3B/u//6T9O+LXhiblcgHOF9aq48GiMA0v8CRo6TZC8OkR6m22RBuyDHNY09Fce+o+s7Wwa4qJX5sj//1i+Zr0NQIo0PF68qGpDqFy8YMKsUT2II2lA+baDmf1PtXMM6uDkslhnSrsgKSsNKiD/3e+GkNtFS5JIJ1dTdimMNMk+8XNL5uZb9Odurh1bxkGh2YYSaGSrLRggAqPt3VNVUPB5ldptY9sYN7RDnBS3I2hwzzfbyordhN1VK5FTTl7QcOmbNuFuDvmuAIt4hw7PqKOOLTiAn0QfBsGBwM8cPTwSbk/svBZaMh5McPYNeL6mjkXPCynHR5QsfLdEMq1B0YB1A+Q9XBjbDtPzB8lPiM8jVMcFMuPnlKnxB4dUi/LPyZg8i2rt0mqnc3IWUSgrau8kIqDr05d+qOsvQz1emA9NRZmQdesdsKVFl/4Gi74BJdXPo8X/zkrEYbUK1E/LbNAIVzuAfe8yybNo2rnQaJUwN4SqdMPrt1NoxuclzOqdmPo8mhlqL27NV4dj
  template:
    metadata:
      name: grafana-oauth-secrets
      namespace: monitoring
